### ISSUE TITLE
AIX rpm resources from oss4aix needs to be replaced

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1387]
The AIX tool `generate_wazuh_packages.sh` uses oss4aix page links to download RPM resources. Those resources are not available now, so we need to search them over the internet and put them into the packages-dev.wazuh.com/deps/aix folder, adapting this tool to use this new URL.

**Comment by DFolchA** [comment]
## Update
We are currently investigating this issue, the dependencies have been uploaded to `packages-dev.wazuh.com`

Currently we are facing an issue when compiling cmake:

- `gmake` would not execute, showing the following error:
```
bash-4.4# gmake
Could not load program gmake:
Symbol resolution failed for /opt/freeware/lib/libguile.a[libguile.so.17] because:
        Symbol pthread_getattr_np (number 260) is not exported from dependent
          module /usr/lib/libpthreads.a[shr_xpg5_64.o].
System error: Error 0
Examine .loader section symbols with the 'dump -Tv' command.
```

It seems that a library invoked by guile cannot load properly. 

Also when executing the bootstrap for cmake the log shows the following error:

```
------------------------------------------
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/system_error:39:0,
                 from /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/bits/ios_base.h:46,
                 from /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/ios:42,
                 from /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/ostream:38,
                 from /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/iostream:39,
                 from cmake_bootstrap_438274_test.cxx:2:
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/powerpc-ibm-aix6.1.0.0/pthread/bits/error_constants.h:135:24: error: 'EOWNERDEAD' was not declared in this scope
       owner_dead =     EOWNERDEAD,
                        ^~~~~~~~~~
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/include/c++/powerpc-ibm-aix6.1.0.0/pthread/bits/error_constants.h:151:34: error: 'ENOTRECOVERABLE' was not declared in this scope
       state_not_recoverable =    ENOTRECOVERABLE,
                                  ^~~~~~~~~~~~~~~
Test failed to compile

```

**Comment by DFolchA** [comment]
## Update

Tested compilation in AIX 6.1TL9 with GCC9:

The package worked correctly in AIX 6.1TL9 but failed in AIX 6.1TL4 with this error in the `ossec.log`
```
2022/03/31 09:22:38 wazuh-modulesd:syscollector: ERROR: Can't load syscollector.
```

Tested compilation with GCC7, GCC8 and GCC9 in AIX 6.1TL4:

Failed compilation with the following error:

```
Symbol aligned_alloc (number 38) is not exported from dependent
          module /usr/lib/libc.a(shr.o).
```

Both these errors are caused by an incompatibility between the libc in AIX 6.1TL4 and GCC versions greater than 6.

Tested compilation in AIX 6.1TL4 using GCC6.2, GCC6.3, GCC6.4,GCC6.5 , failed with error:
```
gmake[4]: Entering directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.2.6/src/shared_modules/rsync/build'
[ 12%] Building CXX object CMakeFiles/rsync.dir/src/rsync.cpp.o
[ 25%] Building CXX object CMakeFiles/rsync.dir/src/rsyncImplementation.cpp.o
Assembler:
/tmp//ccv6hEcZ.s: line 110: Error In Syntax 
/tmp//ccv6hEcZ.s: line 112: Error In Syntax 
/tmp//ccv6hEcZ.s: line 112: Invalid source character 0x40
/tmp//ccv6hEcZ.s: line 112: Error In Syntax 
/tmp//ccv6hEcZ.s: line 4616: Error In Syntax 
/tmp//ccv6hEcZ.s: line 4618: Error In Syntax 
/tmp//ccv6hEcZ.s: line 4618: Invalid source character 0x40
/tmp//ccv6hEcZ.s: line 4618: Error In Syntax 
gmake[4]: *** [CMakeFiles/rsync.dir/build.make:76: CMakeFiles/rsync.dir/src/rsyncImplementation.cpp.o] Error 1
gmake[4]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.2.6/src/shared_modules/rsync/build'
gmake[3]: *** [CMakeFiles/Makefile2:73: CMakeFiles/rsync.dir/all] Error 2
gmake[3]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.2.6/src/shared_modules/rsync/build'
gmake[2]: *** [Makefile:95: all] Error 2
gmake[2]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.2.6/src/shared_modules/rsync/build'
gmake[1]: *** [Makefile:1361: build_shared_modules] Error 2
gmake[1]: Leaving directory '/opt/freeware/src/packages/BUILD/wazuh-agent-4.2.6/src'
gmake: *** [Makefile:722: agent] Error 2
```

**Comment by DFolchA** [comment]
## Update
 Compiled package with gcc6 in AIX 6.1TL9:
- Successful build
- Package works in TL9 and TL4

**Comment by DFolchA** [comment]
## Update

- Investigate and fix issues with python package so Jenkins integrations work
- Investigate issue with libc in different TL versions, seems that the missing symbol belongs to C11.
