### ISSUE TITLE
Fix archlinux package generation

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1273]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2<br>4.3 | Agent | Build | Archlinux |

Building a package for Archlinux, it has been discovered that the build is broken, both in 4.2 and 4.3. This system is not given official support and the development was created by a user but we must correct these errors anyway.

The build in 4.2 shows the following errors:

```
./generate_arch_package.sh -b v4.2.5 --packages-branch 4.2
...
[ 70%] Building CXX object example/CMakeFiles/dbsync_example.dir/main.cpp.o
[ 80%] Linking CXX executable ../bin/dbsync_example
/usr/sbin/ld: /build_wazuh/agent/build/src/wazuh/src/libwazuhext.so: undefined reference to `pthread_yield'
collect2: error: ld returned 1 exit status
make[4]: *** [example/CMakeFiles/dbsync_example.dir/build.make:98: bin/dbsync_example] Error 1
make[4]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/shared_modules/dbsync/build'
make[3]: *** [CMakeFiles/Makefile2:144: example/CMakeFiles/dbsync_example.dir/all] Error 2
make[3]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/shared_modules/dbsync/build'
make[2]: *** [Makefile:101: all] Error 2
make[2]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/shared_modules/dbsync/build'
make[1]: *** [Makefile:1360: build_shared_modules] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../bin/sysinfo_test_tool
make[4]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/data_provider/build'
[100%] Built target sysinfo_test_tool
make[3]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/data_provider/build'
make[2]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src/data_provider/build'
make[1]: Leaving directory '/build_wazuh/agent/build/src/wazuh/src'
make: *** [Makefile:722: agent] Error 2
make: Leaving directory '/build_wazuh/agent/build/src/wazuh/src'
==> ERROR: A failure occurred in build().
    Aborting...
```

4.3 show the following error:

```
./generate_arch_package.sh -b v4.3.0 --packages-branch 4.3
...
+ chmod +x /usr/bin/install
+ su user -c 'makepkg -s'
==> Making package: wazuh-agent 4.3.0-1 (Wed 23 Feb 2022 04:55:08 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found wazuh-agent-4.3.0.tar.gz
  -> Found wazuh.sysusers
==> Validating source files with sha512sums...
    wazuh-agent-4.3.0.tar.gz ... Skipped
    wazuh.sysusers ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

Regards, Raúl

**Comment by alberpilot** [comment]
Solved here: https://github.com/wazuh/wazuh-packages/pull/1650
